---
- name: '[common] ({{ module_meta.name }}) Provision vars'
  debug: var=provision
  tags: debug

- name: '[common] ({{ module_meta.name }}) Ensure the module directory exists'
  file:
    path: '{{ tf_modules_dir }}/{{ module_meta.path }}'
    state: directory

- name: '[common] ({{ module_meta.name }}) Copy the module'
  copy:
    src: 'main.tf'
    dest: '{{ tf_modules_dir }}/{{ module_meta.path }}/main.tf'

- name: '[common] ({{ module_meta.name }}) Template the module signature'
  template:
    src: module.j2
    dest: '{{ tf_modules_dir }}/{{ module_meta.path }}/signature.tf'

- name: '[common] ({{ module_meta.name }}) Template the component'
  template:
    src: component.j2
    dest: '{{ component_dir }}/{{ module_meta.name }}.tf'

- name: '[common] ({{ module_meta.name }}) Add variables to .tfvars'
  blockinfile:
    create: yes
    dest: '{{ tfvars_file }}'
    marker: '# {mark} ANSIBLE MANAGED BLOCK ({{ module_meta.name }})'
    block: |
      {% set module_name = (module_meta.name | replace('-', '_')) %}
      {% for key, value in variables.iteritems() %}
      {{ module_name }}_{{ key }}{{ ' ' * (30 - (key | length)) }}= "{{ provision.tfvars[key] | default(value.default) }}"
      {% endfor %}
