---
- name: '[common] ({{ module_meta.ns }}/{{ module_meta.name }}) Provision vars'
  debug: var=provision
  tags: debug

- name: '[common] ({{ module_meta.ns }}/{{ module_meta.name }}) Template the module'
  template:
    src: main.tf.j2
    dest: '{{ module_dir }}/main.tf'

- name: '[common] ({{ module_meta.ns }}/{{ module_meta.name }}) Template the module signature'
  template:
    src: signature.tf.j2
    dest: '{{ module_dir }}/signature.tf'

- name: '[common] ({{ module_meta.ns }}/{{ module_meta.name }}) Template the component'
  template:
    src: component.j2
    dest: '{{ component_dir }}/main.tf'

- name: '[common] ({{ module_meta.ns }}/{{ module_meta.name }}) Add variables to .tfvars'
  blockinfile:
    create: yes
    dest: '{{ tfvars_file }}'
    marker: '# {mark} ANSIBLE MANAGED BLOCK ({{ module_meta.name }})'
    block: |
      {% set module_name = (module_meta.name | replace('-', '_')) %}
      {% for key, value in variables.iteritems() %}
      {{ module_name }}_{{ key }}{{ ' ' * (40 - (key | length)) }} = "{{ provision.tfvars[key] | default(value.default) }}"
      {% endfor %}
