---
- name: Get the current public IP address of the machine running ansible
  uri:
    url: http://checkip.amazonaws.com/
    return_content: yes
  register: current_ip

- name: Strip the current IP of newline
  set_fact:
    ipt: "{{ current_ip.content | replace('\n', '/32') }}"

- name: Set provision.tfvars.access_cidr to the current IP
  set_fact:
    provision:
      provider: '{{ provision.provider }}'
      remote_state: '{{ provision.remote_state }}'
      tfvars: "{{ provision.tfvars | combine({'access_cidr': ipt}) }}"
