---
- name: '[main] Set module_meta vars'
  set_fact:
    module_meta: "{{ module_vars | combine(module | default({})) }}"

- name: '[main] ({{ module_meta.ns }}/{{ module_meta.name }}) Set component_meta vars'
  set_fact:
    component_meta: "{{ module_meta | combine(component | default({})) }}"

- name: '[main] ({{ module_meta.ns }}/{{ module_meta.name }}) Set instance_meta vars'
  set_fact:
    instance_meta: "{{ component_meta | combine(instance | default({})) }}"

- name: '[main] ({{ module_meta.ns }}/{{ module_meta.name }}) Set var names'
  set_fact:
    component_var_name: "{{ (package + '_' + component_meta.ns + '_' + component_meta.name + '_c') | replace('-', '_') }}"
    instance_var_name: "{{ (package + '_' + instance_meta.ns + '_' + instance_meta.name + '_i') | replace('-', '_') }}"
    # TODO: The next two need to be changed so they can inherit from the instance
    remote_state_var_name: "{{ package | replace('-', '_') }}_remote_state"
    provider_var_name: "{{ package | replace('-', '_') }}_provider"

- name: '[main] ({{ module_meta.ns }}/{{ module_meta.name }}) Component var name'
  debug: var=component_var_name
  tags: debug

- name: '[main] ({{ module_meta.ns }}/{{ module_meta.name }}) Instance var name'
  debug: var=instance_var_name
  tags: debug

- name: '[main] ({{ module_meta.ns }}/{{ module_meta.name }}) Get component values'
  set_fact:
    component_vars: '{{ hostvars[inventory_hostname][component_var_name] | default({}) }}'
    instance_vars: '{{ hostvars[inventory_hostname][instance_var_name] | default({}) }}'

- name: '[main] ({{ module_meta.ns }}/{{ module_meta.name }}) Component vars'
  debug: var=component_vars
  tags: debug

- name: '[main] ({{ module_meta.ns }}/{{ module_meta.name }}) Instance vars'
  debug: var=instance_vars
  tags: debug

- name: '[main] ({{ module_meta.ns }}/{{ module_meta.name }}) Merge component and instance values'
  set_fact:
    provision:
      tfvars: '{{ (component_vars.tfvars | default({})) | combine(instance_vars.tfvars | default({})) }}'
      remote_state: '{{ hostvars[inventory_hostname][remote_state_var_name] }}'
      provider: '{{ hostvars[inventory_hostname][provider_var_name] }}'

- name: '[main] ({{ module_meta.ns }}/{{ module_meta.name }}) Provision vars'
  debug: var=provision
  tags: debug

# - name: Ensure the environment and component directory is clean
#   file:
#     path: '{{ item }}'
#     state: absent
#   with_items:
#     - '{{ module_dir }}'
#     - '{{ component_dir }}'
#     - '{{ instance_dir }}'

- name: '[main] ({{ module_meta.ns }}/{{ module_meta.name }}) Ensure the module, component and instance directory trees exist'
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ module_dir }}'
    - '{{ component_dir }}'
    - '{{ instance_dir }}'

- include: provider.yml
- include: remote-state.yml
