---
- name: Set global vars
  set_fact:
    remote_state_defaults: '{{ hostvars[inventory_hostname][remote_state_var_name] | default({}) }}'
    provider_defaults: '{{ hostvars[inventory_hostname][provider_var_name] | default({}) }}'

- name: Ensure the terragrunt temp directory is clean
  file:
    path: '{{ ansible_env.TMPDIR }}/terragrunt-download'
    state: absent

- name: Ensure the component directory tree exists
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ tf_components_dir }}/{{ package.directory }}'
    - '{{ tf_instances_dir }}/{{ package.directory }}/{{ infrastructure_env }}'

- name: Generate instances global terraform.tfvars
  template:
    src: terraform.tfvars.j2
    dest: '{{ tf_instances_dir }}/terraform.tfvars'
    force: no
